name: deploy

on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Build
        run: |
          yarn
          yarn build
          yarn export

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
